version: '3.8'
services:
  c-auth:
    image: mohammadnowresideh1997/c-auth
    container_name: c-auth
    restart: always
    ports:
      - 3005:3005
    networks:
      - services_app-network

networks:
  services_app-network:
    external: true
