version: '3.8'
services:
  c-auth-staging:
    image: mohammadnowresideh1997/c-auth-staging
    container_name: c-auth-staging
    restart: always
    ports:
      - 3005:3005
    networks:
      - services_app-network

networks:
  services_app-network:
    external: true
